//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLineBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchWord
    {
        public int SearchWordId { get; set; }
        public string SearchWordString { get; set; }
        public int TimelineId { get; set; }
    
        public virtual Timeline Timeline { get; set; }
    }
}
